# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  worker
    spec:
      restartPolicy: Always
      containers:
      - name:  worker
        image:  rmscoal/dalc-worker-app:v0.0.4
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: dalc
              key: db_username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dalc
              key: db_password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: dalc
              key: db_host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: dalc
              key: db_name
        - name: DB_SSLMODE
          value: disable
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: dalc
              key: rabbitmq_username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dalc
              key: rabbitmq_password
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: dalc
              key: rabbitmq_host
        - name: RABBITMQ_VIRTUAL_HOST
          value: /